Resources:
  keyprrTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 'key-store-dev'
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST